export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART"
export const CLEAR_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"

export const CLEAR_CART_REDUCER = "CLEAR_CART_REDUCER"
