export enum Gender {
  MALE = 'Male',
  FEMALE = 'Female',
}

export enum BannerType {
  SLIDER_CAMPAIGN = 'SLIDER_CAMPAIGN',
  SLIDER_HOMEPAGE = 'SLIDER_HOMEPAGE',
  TWO_FIRST = 'TWO_FIRST',
  TWO_LAST = 'TWO_LAST',
  THREE_FIRST = 'THREE_FIRST',
  THREE_MIDDLE = 'THREE_MIDDLE',
  THREE_LAST = 'THREE_LAST',
  POPUP_BANNER = 'POPUP_BANNER',
  SHOP_BY_BANNER_SIDEBAR = 'SHOP_BY_BANNER_SIDEBAR',
  FULL_BANNER = 'FULL_BANNER',
}
