import "@assets/css/app.scss"

import { persistor, store } from "src/@config/redux/store"

import type { AppProps } from "next/app"
import Head from "next/head"
import { PersistGate } from "redux-persist/integration/react"
import { Provider } from "react-redux"

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>SSR with NextJS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					type="text/css"
					href="https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i"
				/>
				<link
					rel="stylesheet"
					type="text/css"
					href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
				/>
				<link
					rel="stylesheet"
					type="text/css"
					href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i"
				/>
			</Head>

			<Provider store={store}>
				<PersistGate persistor={persistor}>
					<Component {...pageProps} />
				</PersistGate>
			</Provider>
		</>
	)
}
export default MyApp
